import { isPresignedUrl, stripPresignParams } from "./requestWatermark";
import { sendLog } from "./sendLog";

// Error reports are rate limited apart from page-load logs. An error often
// happens right after the page loads, inside the page-load log's window.
const ERROR_RATE_LIMIT_KEY = "neurosift-error-log-last-sent";

const ISSUES_URL = "https://github.com/flatironinstitute/neurosift/issues/new";

const MAX_STACK_LINES = 8;

// build-info.json is generated by `npm run dev` and `npm run build`, and is
// absent otherwise (for example when the tests run in CI).
const buildInfo = Object.values(
  import.meta.glob<{ buildTime?: string }>("../build-info.json", {
    eager: true,
    import: "default",
  }),
)[0];

export type ErrorSource = "render" | "window.onerror" | "unhandledrejection";

/**
 * The page url with any presigned-url signature removed, so that a link to a
 * privately shared file does not end up in a log or in a public issue. The
 * file url is sometimes embedded unencoded (its parameters then sit in the
 * page's own query string) and sometimes encoded inside the `url` parameter.
 */
export const pageUrlForReport = (href: string): string =>
  stripPresignParams(href).replace(
    /([?&]url=)([^&#]*)/,
    (whole, name: string, value: string) => {
      try {
        const fileUrl = decodeURIComponent(value);
        return isPresignedUrl(fileUrl)
          ? name + encodeURIComponent(stripPresignParams(fileUrl))
          : whole;
      } catch {
        return whole;
      }
    },
  );

// Duck-typed: a DOMException (an aborted fetch, for one) is not an instance
// of Error in every environment, and errors can cross from an iframe.
const errorFields = (error: unknown) => {
  if (typeof error !== "object" || error === null) return undefined;
  const { name, message, stack } = error as Record<string, unknown>;
  if (typeof message !== "string") return undefined;
  return {
    name: typeof name === "string" ? name : "Error",
    message,
    stack: typeof stack === "string" ? stack : "",
  };
};

const describeError = (error: unknown) => {
  const fields = errorFields(error);
  if (!fields) return { name: "", summary: String(error), stack: "" };
  return {
    name: fields.name,
    summary: `${fields.name}: ${fields.message}`,
    stack: fields.stack.split("\n").slice(0, MAX_STACK_LINES).join("\n"),
  };
};

// Not worth reporting: browser noise that no code change here would fix.
const isIgnored = (name: string, summary: string): boolean =>
  // A request that was canceled on purpose, e.g. when a view unmounts.
  name === "AbortError" ||
  // Chrome reports a benign layout timing condition as an error.
  summary.includes("ResizeObserver loop") ||
  // An error in a cross-origin script, with every detail withheld.
  summary === "Script error.";

export const errorMessage = (error: unknown): string =>
  errorFields(error)?.message ?? String(error);

const reported = new Set<string>();

/**
 * Sends an error to the logging endpoint. The same error is reported once per
 * page load, so a view that throws on every render does not flood the log.
 */
export const reportError = (
  error: unknown,
  o: { source: ErrorSource; componentStack?: string },
): void => {
  const { name, summary, stack } = describeError(error);
  if (isIgnored(name, summary)) return;
  if (reported.has(summary)) return;
  reported.add(summary);

  sendLog(
    {
      message: "Error: " + summary,
      metadata: {
        url: pageUrlForReport(window.location.href),
        source: o.source,
        stack,
        componentStack: o.componentStack
          ?.split("\n")
          .slice(0, MAX_STACK_LINES)
          .join("\n"),
        buildTime: buildInfo?.buildTime,
      },
    },
    ERROR_RATE_LIMIT_KEY,
  );
};

/**
 * Reports errors that no error boundary sees: those thrown from event
 * handlers and timers, and promise rejections that nothing handles.
 */
export const installGlobalErrorReporting = (
  target: Pick<Window, "addEventListener"> = window,
): void => {
  target.addEventListener("error", (event) => {
    reportError(event.error ?? event.message, { source: "window.onerror" });
  });
  target.addEventListener("unhandledrejection", (event) => {
    reportError(event.reason, { source: "unhandledrejection" });
  });
};

/**
 * A link that opens a new GitHub issue with the page url and the error filled
 * in, following what CONTRIBUTING.md asks for in a report.
 */
export const issueUrlForError = (
  error: unknown,
  what: string,
  href: string = window.location.href,
): string => {
  const { summary, stack } = describeError(error);
  const title = `Error in ${what}: ${summary}`.slice(0, 120);
  const body = [
    "**Link to the visualization**",
    pageUrlForReport(href),
    "",
    "**Error**",
    "```",
    stack || summary,
    "```",
    "",
    "**What I was doing and what I expected**",
    "<!-- Please describe it here, and attach a screenshot if you can. -->",
    "",
    ...(buildInfo?.buildTime
      ? [`Neurosift build: ${buildInfo.buildTime}`]
      : []),
    `Browser: ${navigator.userAgent}`,
  ].join("\n");
  return `${ISSUES_URL}?${new URLSearchParams({ title, body })}`;
};

// For tests.
export const resetReportedErrors = () => reported.clear();
